# Generated by Django 2.2.2 on 2019-10-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191015_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missao',
            old_name='categoria',
            new_name='conclusao',
        ),
    ]
