# Generated by Django 2.2.6 on 2019-10-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191015_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missao',
            name='conclusao',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Inconcluída', 'Inconcluída')], max_length=12),
        ),
    ]
