# Generated by Django 2.2.6 on 2019-11-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191021_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='posicao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
